[package]
name = "multinode_integration_tests"
version = "0.4.1"
authors = ["Substratum Developer <substratum@substratum.net>"]
license = "GPL-3.0-only"
copyright = "Copyright (c) 2017-2019, Substratum LLC (https://substratum.net) and/or its affiliates. All rights reserved."
description = ""
workspace = "../node"

[dependencies]
base64 = "0.10.0"
regex = "1.0.5"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_cbor = "0.9.0"
sub_lib = { path = "../sub_lib" }
hopper_lib = { path = "../hopper_lib" }
neighborhood_lib = { path = "../neighborhood_lib" }
node = { path = "../node" }
test_utils = { path = "../test_utils" }

[lib]
name = "multinode_integration_tests_lib"
path = "src/lib.rs"

[[bin]]
name = "MockNode"
path = "src/main.rs"