[package]
name = "dns_utility"
version = "0.4.1"
license = "GPL-3.0-only"
authors = ["Substratum Services"]
copyright = "Copyright (c) 2017-2019, Substratum LLC (https://substratum.net) and/or its affiliates. All rights reserved."
description = "Command-line utility to turn DNS subversion on and off"

[dependencies]
regex = "1.0.5"
sub_lib = { path = "../sub_lib" }
libc = "0.2.43"

[target.'cfg(target_os = "macos")'.dependencies]
system-configuration = "0.1.0"
core-foundation = "0.5.1"

[target.'cfg(windows)'.dependencies]
winreg = "0.5.1"

[dev-dependencies]
test_utils = {path = "../test_utils" }

[[bin]]
name = "dns_utility"
path = "src/main.rs"

[lib]
name = "dns_utility_lib"
path = "src/lib.rs"

cargo-bundle = "0.4.0"