[package]
name = "node"
version = "0.4.1"
license = "GPL-3.0-only"
authors = ["Substratum Services"]
copyright = "Copyright (c) 2017-2019, Substratum LLC (https://substratum.net) and/or its affiliates. All rights reserved."
description = ""

[workspace]
members = ["../sub_lib", "../test_utils", "../entry_dns_lib", "../hopper_lib", "../neighborhood_lib", "../proxy_client_lib", "../proxy_server_lib", "../multinode_integration_tests"]

[dependencies]
actix = "= 0.5.7" # upgrading causes flakiness
base64 = "0.10.0"
chrono = "0.4.6"
flexi_logger = "0.10.0"
futures = "0.1.25"
log = "0.4.6"
regex = "1.0.5"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
serde_cbor = "0.9.0"
tokio = "0.1.11"
sub_lib = { path = "../sub_lib" }
entry_dns_lib = { path = "../entry_dns_lib" }
neighborhood_lib = { path = "../neighborhood_lib" }
proxy_server_lib = { path = "../proxy_server_lib" }
proxy_client_lib = { path = "../proxy_client_lib" }
hopper_lib = { path = "../hopper_lib" }

[dev-dependencies]
tls-api = "0.1.20"
tls-api-native-tls = "0.1.20"
test_utils = { path = "../test_utils" }

[target.'cfg(unix)'.dependencies]
daemonize = "0.3.0"

[target.'cfg(windows)'.dependencies]

[[bin]]
name = "SubstratumNode"
path = "src/main.rs"

[lib]
name = "node_lib"
path = "src/lib.rs"

cargo-bundle = "0.4.0"